
# 决斗系列插件 设置
duel_cfg: 
  # 战斗力依赖系数
  Magnification: 2
  # 命令间隔时间，单位秒，这是决斗的冷却时间#初始为300秒
  Cooling_time: 300
  # 命令间隔时间，单位分钟，这是锻炼的冷却时间#初始为300分钟
  cdtime_exercise: 300
  # 命令间隔时间，单位分钟，这是突破的冷却时间#初始为30分钟
  cdtime_break: 30
# 娶群友系列配置
wife_cfg:
  #概率,单位(成)
  #强娶老婆成功率
  qqwife: 3
  #随机娶群友成功概率
  sjwife: 5
  #冷却时间,单位(分)
  #随机娶冷却
  sjcd: 5
  #强娶冷却
  qqcd: 10
  #打工冷却
  dgcd: 20
  #抱抱冷却
  bbcd: 60
  #逛街冷却
  ggcd: 45
  #抢老婆冷却
  qlpcd: 20
  #领取低保冷却
  poorcd: 1440
  #获取虚空彩球的cd
  RBBgetcd: 720
  #行动限制,单位(次)
  #逛街->去下一个地方
  gifttime: 5
  #虚空彩球
  #开奖通知主人 F关 T开
  notice: 'F'
  #开奖通知群
  group:
    - 123456789
    - 123123123
  #开奖时间,单位(24制-时0到23)
  RBBtime: 20